import type { Farm, EcoMarket, CropCategory, TrustTier } from './db';

// ── Crop Category Color Map ────────────────────────────────────────────────────
export const CROP_CATEGORY_COLORS: Record<CropCategory, string> = {
  leafy:  '#22C55E',   // green
  grain:  '#EAB308',   // yellow
  root:   '#F97316',   // orange
  cash:   '#A855F7',   // purple
  legume: '#3B82F6',   // blue
  fruit:  '#EC4899',   // pink
};

export const CROP_CATEGORY_LABELS: Record<CropCategory, string> = {
  leafy:  '🥬 Leafy / Vegetables',
  grain:  '🌽 Grains',
  root:   '🥔 Root Crops',
  cash:   '☕ Cash Crops',
  legume: '🫘 Legumes',
  fruit:  '🍌 Fruits',
};

// ── Mock GIS Farms (Central Uganda – real coords) ─────────────────────────────
export const mockFarmsGIS: Farm[] = [
  {
    id: 'farm-001',
    farmerId: 'farmer-001',
    name: 'Mukasa Organic Plantation',
    lat: 0.3270,
    lng: 32.5753,
    cropType: 'Matooke',
    cropCategory: 'fruit',
    plotSizeHa: 2.4,
    is_certified_organic: true,
    trust_tier: 'high',
    sustainability_score: 92,
    audited_by: 'Uganda Organic Certification',
    last_audit: '2026-01-15',
    phone: '+256 701 234 567',
  },
  {
    id: 'farm-002',
    farmerId: 'farmer-002',
    name: 'Nakato Maize Cooperative',
    lat: 0.3580,
    lng: 32.6110,
    cropType: 'Maize',
    cropCategory: 'grain',
    plotSizeHa: 5.1,
    is_certified_organic: false,
    trust_tier: 'verified',
    sustainability_score: 74,
    audited_by: 'EcoFarm Auditor',
    last_audit: '2025-11-20',
  },
  {
    id: 'farm-003',
    farmerId: 'farmer-003',
    name: 'Ssali Cassava Gardens',
    lat: 0.2950,
    lng: 32.6420,
    cropType: 'Cassava',
    cropCategory: 'root',
    plotSizeHa: 3.8,
    is_certified_organic: false,
    trust_tier: 'verified',
    sustainability_score: 68,
  },
  {
    id: 'farm-004',
    farmerId: 'farmer-004',
    name: 'Namirembe Beans Farm',
    lat: 0.3120,
    lng: 32.5400,
    cropType: 'Climbing Beans',
    cropCategory: 'legume',
    plotSizeHa: 1.5,
    is_certified_organic: true,
    trust_tier: 'high',
    sustainability_score: 88,
    audited_by: 'Fair Trade Uganda',
    last_audit: '2026-02-10',
    phone: '+256 702 345 678',
  },
  {
    id: 'farm-005',
    farmerId: 'farmer-005',
    name: 'Kato Coffee Estate',
    lat: 0.2800,
    lng: 32.5200,
    cropType: 'Arabica Coffee',
    cropCategory: 'cash',
    plotSizeHa: 8.2,
    is_certified_organic: true,
    trust_tier: 'high',
    sustainability_score: 96,
    audited_by: 'Rainforest Alliance',
    last_audit: '2025-12-01',
    phone: '+256 703 456 789',
  },
  {
    id: 'farm-006',
    farmerId: 'farmer-006',
    name: 'Namubiru Spinach Patch',
    lat: 0.3800,
    lng: 32.5650,
    cropType: 'Spinach',
    cropCategory: 'leafy',
    plotSizeHa: 0.8,
    is_certified_organic: false,
    trust_tier: 'pending',
    sustainability_score: 55,
  },
  {
    id: 'farm-007',
    farmerId: 'farmer-007',
    name: 'Opio Sorghum Fields',
    lat: 0.4100,
    lng: 32.6300,
    cropType: 'Sorghum',
    cropCategory: 'grain',
    plotSizeHa: 6.5,
    is_certified_organic: false,
    trust_tier: 'pending',
    sustainability_score: 61,
  },
  {
    id: 'farm-008',
    farmerId: 'farmer-008',
    name: 'Auma Sweet Potato Farm',
    lat: 0.2600,
    lng: 32.5900,
    cropType: 'Sweet Potato',
    cropCategory: 'root',
    plotSizeHa: 2.0,
    is_certified_organic: true,
    trust_tier: 'verified',
    sustainability_score: 79,
    audited_by: 'Ministry of Agriculture',
    last_audit: '2025-09-30',
  },
  {
    id: 'farm-009',
    farmerId: 'farmer-009',
    name: 'Wasswa Kale Gardens',
    lat: 0.3450,
    lng: 32.5100,
    cropType: 'Kale (Nakati)',
    cropCategory: 'leafy',
    plotSizeHa: 0.6,
    is_certified_organic: false,
    trust_tier: 'unverified',
    sustainability_score: 38,
  },
  {
    id: 'farm-010',
    farmerId: 'farmer-010',
    name: 'Okello Simsim Estate',
    lat: 0.4300,
    lng: 32.5500,
    cropType: 'Simsim (Sesame)',
    cropCategory: 'cash',
    plotSizeHa: 4.1,
    is_certified_organic: false,
    trust_tier: 'verified',
    sustainability_score: 71,
  },
];

// ── Mock Eco-Conscious Markets ─────────────────────────────────────────────────
export const mockEcoMarkets: EcoMarket[] = [
  {
    id: 'market-001',
    name: 'Kalerwe Organic Hub',
    lat: 0.3481,
    lng: 32.5780,
    type: 'eco_buyer',
    accepts_organic: true,
    description: 'Premium organic produce buyer. Pays 25% above market rate.',
  },
  {
    id: 'market-002',
    name: 'Nakasero Fresh Market',
    lat: 0.3161,
    lng: 32.5856,
    type: 'market',
    accepts_organic: true,
    description: 'Central Kampala market. Accepts certified and conventional produce.',
  },
  {
    id: 'market-003',
    name: 'EcoFarm Cooperative — Ntinda',
    lat: 0.3520,
    lng: 32.6230,
    type: 'cooperative',
    accepts_organic: true,
    description: 'Farmer-owned cooperative. Bulk purchase agreements available.',
  },
  {
    id: 'market-004',
    name: 'Green Basket — Bukoto',
    lat: 0.3310,
    lng: 32.6050,
    type: 'eco_buyer',
    accepts_organic: true,
    description: 'Eco-conscious supermarket sourcing only verified organic farms.',
  },
  {
    id: 'market-005',
    name: 'Wandegeya Community Market',
    lat: 0.3360,
    lng: 32.5670,
    type: 'market',
    accepts_organic: false,
    description: 'Community market. High footfall. Mixed produce accepted.',
  },
];

// ── Mock Market Prices (UGX per kg) ───────────────────────────────────────────
export const mockMarketPrices = [
  { cropId: 'matooke',     cropName: 'Matooke',         pricePerKg: 1500, marketName: 'Kalerwe' },
  { cropId: 'maize',       cropName: 'Maize',            pricePerKg: 900,  marketName: 'Nakasero' },
  { cropId: 'beans',       cropName: 'Climbing Beans',   pricePerKg: 3800, marketName: 'Nakasero' },
  { cropId: 'cassava',     cropName: 'Cassava',          pricePerKg: 700,  marketName: 'Wandegeya' },
  { cropId: 'sorghum',     cropName: 'Sorghum',          pricePerKg: 1200, marketName: 'Ntinda Coop' },
  { cropId: 'simsim',      cropName: 'Simsim (Sesame)',  pricePerKg: 6500, marketName: 'Kalerwe' },
  { cropId: 'coffee',      cropName: 'Arabica Coffee',   pricePerKg: 12000, marketName: 'Green Basket' },
  { cropId: 'sweetpotato', cropName: 'Sweet Potato',     pricePerKg: 1100, marketName: 'Nakasero' },
  { cropId: 'spinach',     cropName: 'Spinach',          pricePerKg: 2500, marketName: 'Wandegeya' },
  { cropId: 'kale',        cropName: 'Kale (Nakati)',    pricePerKg: 2200, marketName: 'Kalerwe' },
];

// ─── Re-export existing types ──────────────────────────────────────────────────
export type { WeatherStatus, CropStatus, PestSeverity } from './mockData';
